# stack updated: 27.10.2018
version: '2'

services:
  postgres:
    image: postgres:10
    container_name: asciinema_postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    container_name: asciinema_redis
    restart: unless-stopped
    volumes:
      - redis:/data

  smtp:
    image: namshi/smtp
    container_name: asciinema_smtp
    restart: unless-stopped
    env_file: .env.production

  nginx:
    image: nginx:1.13-alpine
    container_name: asciinema_nginx
    restart: unless-stopped
    links:
      - phoenix
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - cache:/cache

  phoenix:
    image: asciinema/asciinema-server@sha256:fd6343e99215738d4eefb13e331dcbd0947c908b67b3909c7184f04fffdfed80
    command: mix phx.server
    container_name: asciinema_phoenix
    restart: unless-stopped
    links:
      - redis
      - postgres
      - smtp
    env_file: .env.production
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: {}
  cache: {}
  postgres: {}
  redis: {}
