version: '2'

services:
  postgres:
    image: postgres
    container_name: asciinema_postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: asciinema_redis
    restart: unless-stopped
    volumes:
      - redis:/data

  smtp:
    image: namshi/smtp
    container_name: asciinema_smtp
    restart: unless-stopped
    env_file: .env.production

  nginx:
    image: nginx:alpine
    container_name: asciinema_nginx
    restart: unless-stopped
    links:
      - phoenix
      - rails
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - cache:/cache

  phoenix:
    image: asciinema/asciinema-server:develop
    command: mix phx.server
    container_name: asciinema_phoenix
    restart: unless-stopped
    links:
      - redis
      - postgres
      - smtp
    env_file: .env.production
    volumes:
      - uploads:/app/uploads
      - web:/tmp

  rails:
    image: asciinema/asciinema-server:develop
    command: bundle exec unicorn -c config/unicorn.rb
    container_name: asciinema_rails
    restart: unless-stopped
    links:
      - redis
      - postgres
    env_file: .env.production
    volumes:
      - uploads:/app/uploads
      - log:/app/log
      - web:/tmp
      - tmp:/app/tmp

volumes:
  log: {}
  uploads: {}
  cache: {}
  postgres: {}
  redis: {}
  tmp: {}
  web: {}

